[package]
name = "sxt-proof-of-sql-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-serialize = { version = "0.4.0", default-features = false }
clap = { version = "4.5.20", features = ["derive", "env"] }
dotenv = "0.15"
flexbuffers = { version = "2.0.0" }
futures = { version = "0.3.31"}
postcard = { version = "1.0.10", default-features = false }
proof-of-sql = { version = "0.33.15" }
proof-of-sql-parser = { version = "0.33.15" }
prost = "0.12"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
subxt = "0.37.0"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
tonic = { version = "0.11", features = ["tls", "tls-roots"] }

[dev-dependencies]
log = "0.4.22"
indexmap = "2.6.0"
futures = "0.3.31"

[build-dependencies]
prost-build = "0.12"
tonic-build = { version = "0.11" }
