[package]
name = "sxt-proof-of-sql-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = { version = "0.4.0", features = [ "parallel" ] }
curve25519-dalek = { version = "4", features = ["rand_core"] }
flexbuffers = { version = "2.0.0" }
proof-of-sql = { version = "0.12.3", default-features = false, features = ["blitzar", "test"] }
proof-of-sql-parser = { version = "0.12.3" }
prost = "0.12"
serde = { version = "1.0", features = ["serde_derive"] }
subxt = "0.37.0"
subxt-signer = "0.37.0"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
tonic = { version = "0.11", features = ["tls", "tls-roots"] }

[build-dependencies]
prost-build = "0.12"
tonic-build = { version = "0.11" }
