[package]
name = "sxt-proof-of-sql-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = { version = "0.4.0", features = [ "parallel" ] }
flexbuffers = { version = "2.0.0" }
proof-of-sql = { version = "0.22.12", default-features = false, features = ["test"] }
prost = "0.12"
serde = { version = "1.0", features = ["serde_derive"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
tonic = { version = "0.11", features = ["tls", "tls-roots"] }

[build-dependencies]
prost-build = "0.12"
tonic-build = { version = "0.11" }
